### ISSUE TITLE
Use JSON schemas (instead of writing mongoose schemas)?

### ISSUE THREAD

**Issue by iaincollins** [glitchdigital/structured-data-api#6]
Right now we have simple schemas written for Mongoose. 

These are easy to read and programatically extend if we want to customise the behaviour.

Alternatively, we could add support for standard JSON schemas and load them as mongoose objects.

Example JSON schema:
http://json-schema.org/examples.html

There is an existing NPM package which would do the work for us:
https://www.npmjs.com/package/json-schema-to-mongoose

Things like types, default values and validation regexs are supported by JSON schemas so they are pretty powerful.

An argument in favour is it wouldn't require any coding to create new schemas, it's easier to write them without mistakes (because the schemas themselves have to be valid to work) and you could just easily import them from elsewhere. We should also be easily able to generate JSON-LD from a JSON schema.

An argument against is that while it's a nice abstraction there isn't currently a practical requirement for it.

Should we do this? Thoughts welcome.

cc @jacqui @leihelondon

**Comment by jacqui** [comment]
Sure, json schemas sound good to me. Go for it! +1
